[project]
name = "dqc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "pandas>=2.3.1",
    "psycopg>=3.2.9",
    "sqlalchemy>=2.0.41",
]
